"""One-time bootstrap for the 435-district HOUSE_RACES/DISTRICT_FUNDAMENTALS
registries, from live Wikipedia data (see app.ingestion.house_scraper).

Unlike scripts/seed_pollster_ratings.py, this does NOT upsert a DB table --
it WRITES two generated Python source files, app/seed/house_seed_data.py
(HOUSE_RACES) and app/data/district_fundamentals_data.py
(DISTRICT_FUNDAMENTALS), since Governor/Senate/House all need to stay
git-tracked, hand-editable static registries (see the existing
app/seed/seed_data.py) -- e.g. for later manually adding a real declared
challenger, photo_url, kalshi_ticker, or real polls once they exist, the
same way every existing Governor/Senate entry was refined by hand over
time.

Every district is seeded with whatever this run could confidently confirm
from Wikipedia -- never a fabricated challenger. A confirmed sitting
incumbent (name + party read directly from the page's Member/Party
columns, independent of the messier Candidates cell) is included as a
candidate only when the page's own Status text says they're actually
still in the race (not retiring/resigned/defeated/died); any additional
candidate is included only when the "Candidates" cell narrows cleanly to a
real settled field (see house_scraper._settled_general_field). A district
where neither confirms cleanly is left with fewer than 2 candidates rather
than guessing -- that's expected for a meaningful share of the 435 today
and gets filled in incrementally, same precedent as SC's empty raw_polls.

Re-running this later to pick up newly-settled primaries will REGENERATE
both files from scratch and will NOT preserve any hand-edits made since
the last run -- treat this as a one-time bootstrap, same caveat
scripts/seed_pollster_ratings.py documents for its own refresh cadence.

Usage (from inside the backend container or a matching venv):
    python -m scripts.generate_house_seed_data
"""

import logging
import re
from pathlib import Path

from app.ingestion.house_scraper import RedistrictingStatus, ScrapedDistrict, fetch_all_districts, fetch_redistricting_changes

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

ELECTION_DATE = "2026-11-03"

_STILL_RUNNING_MARKERS = ("renominated", "running", "advanced to general", "re-elected")
_INVALID_NAME_MARKERS = ("none", "vacant", "tbd")

_REPO_ROOT = Path(__file__).resolve().parent.parent
_HOUSE_SEED_PATH = _REPO_ROOT / "app" / "seed" / "house_seed_data.py"
_DISTRICT_FUNDAMENTALS_PATH = _REPO_ROOT / "app" / "data" / "district_fundamentals_data.py"

_HOUSE_SEED_HEADER = '''"""U.S. House race registry, keyed by a 4-char district key (2-letter
state_code + zero-padded 2-digit district number, e.g. "ca12"; at-large
states use "01"). Same shape as app.seed.seed_data.RACES/SENATE_RACES, one
entry per district.

Generated by backend/scripts/generate_house_seed_data.py (see that script's
docstring) from live Wikipedia sources -- this file is git-tracked and
hand-editable afterward (e.g. adding a real challenger, photo_url,
kalshi_ticker, or real polls once they exist), the same way every existing
Governor/Senate entry in seed_data.py was refined by hand over time.
Re-running the generator script will overwrite any hand-edits made since
the last run.
"""

HOUSE_RACES: dict = {
'''

_DISTRICT_FUNDAMENTALS_HEADER = '''"""Real historical inputs for the House district-fundamentals model (see
app.services.fundamentals.district_fundamentals_breakdown), keyed by the
same 4-char district key as app.seed.house_seed_data.HOUSE_RACES (2-letter
state_code + zero-padded 2-digit district number, e.g. "ca12").

Unlike app.data.fundamentals_data.RACE_FUNDAMENTALS (one entry per *state*,
blending that state's own gubernatorial/Senate/presidential history), a
single congressional district has no gubernatorial or Senate race of its
own -- the two genuinely district-level inputs here are (a) the district's
Cook Partisan Voting Index (`pvi_dem_margin_pts`, a signed point value,
positive favors the Democratic candidate -- parsed from Cook's own
"D+N"/"R+N"/"EVEN" notation, as cited by Wikipedia's 2026 House-elections
page, itself already computed on the district's *current* 2026 lines, so
no separate recency-weighting is needed the way a raw multi-year election
series gets), and (b) the district's own last 1-2 House election results
(`house_elections`, recency-weighted the same way as RACE_FUNDAMENTALS --
see fundamentals.district_lean). No registration-trend input -- unlike
statewide races, no per-district voter-registration dataset exists.

Generated by backend/scripts/generate_house_seed_data.py alongside
app.seed.house_seed_data.HOUSE_RACES. `house_elections` starts as an empty
list for every district -- app.services.fundamentals._recency_weighted_dem_margin
already treats an empty list as a neutral 0 -- since no per-district prior
House results have been backfilled yet (a distinct, larger follow-up; no
single clean public dataset for this was confirmed when scoped). A district
whose PVI couldn't be parsed gets `pvi_dem_margin_pts: None`, degrading to
the same neutral-0 treatment rather than a fabricated value.
"""

DISTRICT_FUNDAMENTALS: dict = {
'''


def _district_key(state_code: str, district: int) -> str:
    return f"{state_code}{district:02d}"


def _parse_pvi_dem_margin(pvi: str | None) -> float | None:
    """Cook PVI's own "D+N" / "R+N" / "EVEN" notation, converted to a signed
    Democratic-margin point value (positive favors the Democratic
    candidate) -- see app.services.fundamentals.district_lean. None when no
    PVI was scraped for this district (left out of DISTRICT_FUNDAMENTALS
    rather than guessed at -- district_lean degrades to using only
    house_elections, same no-fabrication convention as everywhere else)."""
    if not pvi:
        return None
    pvi = pvi.strip().upper()
    if pvi == "EVEN":
        return 0.0
    match = re.match(r"^([DR])\+(\d+(?:\.\d+)?)$", pvi)
    if not match:
        logger.warning("unrecognized PVI format %r -- leaving pvi_dem_margin_pts unset", pvi)
        return None
    party, points = match.groups()
    return float(points) if party == "D" else -float(points)


def _is_valid_incumbent(d: ScrapedDistrict) -> bool:
    if d.is_open_seat or not d.incumbent_name:
        return False
    name_lower = d.incumbent_name.lower()
    if any(marker in name_lower for marker in _INVALID_NAME_MARKERS):
        return False
    if any(ch.isdigit() for ch in d.incumbent_name):
        return False
    return any(marker in d.status.lower() for marker in _STILL_RUNNING_MARKERS)


def _build_candidates(d: ScrapedDistrict) -> list[dict]:
    candidates: list[dict] = []
    incumbent_valid = _is_valid_incumbent(d)
    if incumbent_valid:
        candidates.append(
            {"name": d.incumbent_name, "party": d.incumbent_party, "incumbent": True}
        )

    for c in d.candidates:
        if incumbent_valid and c.name == d.incumbent_name:
            continue  # already added above as the incumbent -- avoid a duplicate
        candidates.append({"name": c.name, "party": c.party, "incumbent": False})
    return candidates


def _format_candidate(c: dict, indent: str) -> str:
    return (
        f'{indent}{{"name": {c["name"]!r}, "party": {c["party"]!r}, '
        f'"incumbent": {c["incumbent"]!r}, "photo_url": None, "kalshi_ticker": None}},'
    )


def _format_house_race_entry(
    d: ScrapedDistrict, candidates: list[dict], redistricting: RedistrictingStatus | None
) -> str:
    key = _district_key(d.state_code, d.district)
    lines: list[str] = []
    if redistricting is not None and redistricting.status == "New districts enacted":
        lines.append(f"    # {d.state_name} enacted new district lines for 2026 (see Wikipedia's")
        lines.append('    # "Mid-decade redistricting changes" table) -- some such maps remain under')
        lines.append(f"    # active litigation as of generation time. {redistricting.notes[:200]!r}")
    lines.append(f'    "{key}": {{')
    lines.append(f"        {'state_name'!r}: {d.state_name!r},")
    lines.append('        "office": "House",')
    lines.append(f"        \"district\": {d.district},")
    lines.append(f'        "election_date": "{ELECTION_DATE}",')
    lines.append(f"        \"wikipedia_page_title\": {d.wikipedia_page_title!r},")
    if d.pvi:
        lines.append(f"        # 2025 Cook PVI (via Wikipedia, citing The Cook Political Report): {d.pvi}")
    lines.append('        "candidates": [')
    for c in candidates:
        lines.append(_format_candidate(c, "            "))
    lines.append("        ],")
    lines.append('        "raw_polls": [],')
    lines.append("    },")
    return "\n".join(lines)


def _format_district_fundamentals_entry(d: ScrapedDistrict) -> str:
    key = _district_key(d.state_code, d.district)
    pvi_dem_margin = _parse_pvi_dem_margin(d.pvi)
    lines: list[str] = []
    if d.pvi:
        lines.append(f"    # {d.state_name} {d.district}: 2025 Cook PVI {d.pvi} (via Wikipedia)")
    lines.append(f'    "{key}": {{')
    if pvi_dem_margin is not None:
        lines.append(f'        "pvi_dem_margin_pts": {pvi_dem_margin!r},')
    else:
        lines.append('        "pvi_dem_margin_pts": None,  # not scraped -- see district_lean\'s handling')
    lines.append('        "house_elections": [],')
    lines.append("    },")
    return "\n".join(lines)


def main() -> None:
    logger.info("fetching House district data from Wikipedia...")
    districts = fetch_all_districts()
    if not districts:
        logger.warning("scrape returned no districts -- files left unchanged")
        return

    redistricting = fetch_redistricting_changes()
    districts_sorted = sorted(districts, key=lambda d: (d.state_code, d.district))

    house_entries = []
    fundamentals_entries = []
    n_with_incumbent = 0
    n_with_full_field = 0
    for d in districts_sorted:
        candidates = _build_candidates(d)
        if _is_valid_incumbent(d):
            n_with_incumbent += 1
        if len(candidates) >= 2:
            n_with_full_field += 1
        house_entries.append(_format_house_race_entry(d, candidates, redistricting.get(d.state_name)))
        fundamentals_entries.append(_format_district_fundamentals_entry(d))

    _HOUSE_SEED_PATH.write_text(_HOUSE_SEED_HEADER + "\n".join(house_entries) + "\n}\n")
    _DISTRICT_FUNDAMENTALS_PATH.write_text(
        _DISTRICT_FUNDAMENTALS_HEADER + "\n".join(fundamentals_entries) + "\n}\n"
    )

    logger.info(
        "wrote %d districts to %s and %s (%d with a confirmed incumbent candidate, "
        "%d with a full 2-candidate field)",
        len(districts_sorted), _HOUSE_SEED_PATH, _DISTRICT_FUNDAMENTALS_PATH,
        n_with_incumbent, n_with_full_field,
    )


if __name__ == "__main__":
    main()
