"""Real, publicly reported topline polling for each state's 2026 governor
race, keyed by state_code. Each race's polls are compiled from its Wikipedia
polling table plus each poll's own release where it could be located
independently.

`undecided_pct` is the complement (100 - candidate_a% - candidate_b%),
folding in any third-party/"other" share alongside true undecideds, since
this schema tracks only the two major-party candidates.
"""

PA_WIKI_SOURCE = "https://en.wikipedia.org/wiki/2026_Pennsylvania_gubernatorial_election"
OH_WIKI_SOURCE = "https://en.wikipedia.org/wiki/2026_Ohio_gubernatorial_election"
GA_WIKI_SOURCE = "https://en.wikipedia.org/wiki/2026_Georgia_gubernatorial_election"
NY_WIKI_SOURCE = "https://en.wikipedia.org/wiki/2026_New_York_gubernatorial_election"
TX_WIKI_SOURCE = "https://en.wikipedia.org/wiki/2026_Texas_gubernatorial_election"
FL_WIKI_SOURCE = "https://en.wikipedia.org/wiki/2026_Florida_gubernatorial_election"

RACES = {
    "pa": {
        "state_name": "Pennsylvania",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_Pennsylvania_gubernatorial_election",
        "candidates": [
            {"name": "Josh Shapiro", "party": "Democratic", "incumbent": True},
            {"name": "Stacy Garrity", "party": "Republican", "incumbent": False},
        ],
        # Release dates for polls where the exact release day wasn't
        # confirmed in source reporting (both F&M polls, and the
        # PennLive/MAD Global Strategy polls) are reconstructed from
        # field-close + that outlet's typical turnaround (~2-5 days);
        # sample size, MoE, and toplines are all as published. PennLive and
        # MAD Global Strategy are sourced to the Wikipedia polling table
        # itself, since an independently reachable press release couldn't
        # be located for them.
        "raw_polls": [
            {
                "pollster": "Susquehanna Polling & Research",
                "sponsor": None,
                "field_start_date": "2025-09-22",
                "field_end_date": "2025-09-28",
                "release_date": "2025-10-03",
                "sample_size": 700,
                "population": "LV",
                "margin_of_error": 3.7,
                "undecided_pct": 10.0,
                "source_url": "https://www.newsweek.com/republicans-chances-defeating-josh-shapiro-pennsylvania-poll-10845075",
                "results": {"Josh Shapiro": 54.0, "Stacy Garrity": 36.0},
            },
            {
                "pollster": "Quinnipiac University",
                "sponsor": None,
                "field_start_date": "2025-09-25",
                "field_end_date": "2025-09-29",
                "release_date": "2025-10-01",
                "sample_size": 1579,
                "population": "RV",
                "margin_of_error": 3.3,
                "undecided_pct": 6.0,
                "source_url": "https://poll.qu.edu/poll-release?releaseid=3933",
                "results": {"Josh Shapiro": 55.0, "Stacy Garrity": 39.0},
            },
            {
                "pollster": "Franklin & Marshall College",
                "sponsor": None,
                "field_start_date": "2026-02-18",
                "field_end_date": "2026-03-01",
                "release_date": "2026-03-04",
                "sample_size": 834,
                "population": "RV",
                "margin_of_error": 4.1,
                "undecided_pct": 24.0,
                "source_url": "https://www.fandmpoll.org/franklin-marshall-poll-release-march-2026/",
                "results": {"Josh Shapiro": 48.0, "Stacy Garrity": 28.0},
            },
            {
                "pollster": "Quinnipiac University",
                "sponsor": None,
                "field_start_date": "2026-02-19",
                "field_end_date": "2026-02-23",
                "release_date": "2026-02-25",
                "sample_size": 836,
                "population": "RV",
                "margin_of_error": 4.7,
                "undecided_pct": 8.0,
                "source_url": "https://poll.qu.edu/poll-release?releaseid=3948",
                "results": {"Josh Shapiro": 55.0, "Stacy Garrity": 37.0},
            },
            {
                "pollster": "Susquehanna Polling & Research",
                "sponsor": None,
                "field_start_date": "2026-03-18",
                "field_end_date": "2026-03-29",
                "release_date": "2026-04-02",
                "sample_size": 700,
                "population": "LV",
                "margin_of_error": 3.7,
                "undecided_pct": 6.0,
                "source_url": "https://www.politicspa.com/susquehanna-poll-shapiro-holds-commanding-lead-over-garrity/146021/",
                "results": {"Josh Shapiro": 58.0, "Stacy Garrity": 36.0},
            },
            {
                "pollster": "PennLive",
                "sponsor": None,
                "field_start_date": "2026-05-20",
                "field_end_date": "2026-05-24",
                "release_date": "2026-05-28",
                "sample_size": 683,
                "population": "LV",
                "margin_of_error": 5.0,
                "undecided_pct": 18.0,
                "source_url": PA_WIKI_SOURCE,
                "results": {"Josh Shapiro": 53.0, "Stacy Garrity": 29.0},
            },
            {
                "pollster": "MAD Global Strategy",
                "sponsor": None,
                "field_start_date": "2026-06-09",
                "field_end_date": "2026-06-11",
                "release_date": "2026-06-13",
                "sample_size": 600,
                "population": "LV",
                "margin_of_error": 4.0,
                "undecided_pct": 21.0,
                "source_url": PA_WIKI_SOURCE,
                "results": {"Josh Shapiro": 48.0, "Stacy Garrity": 31.0},
            },
            {
                "pollster": "Franklin & Marshall College",
                "sponsor": None,
                "field_start_date": "2026-06-08",
                "field_end_date": "2026-06-14",
                "release_date": "2026-06-18",
                "sample_size": 546,
                "population": "RV",
                "margin_of_error": 5.1,
                "undecided_pct": 22.0,
                "source_url": "https://www.fandmpoll.org/franklin-marshall-college-poll-release-june-2026/",
                "results": {"Josh Shapiro": 50.0, "Stacy Garrity": 28.0},
            },
            {
                "pollster": "PennLive",
                "sponsor": None,
                "field_start_date": "2026-06-18",
                "field_end_date": "2026-06-25",
                "release_date": "2026-06-29",
                "sample_size": 644,
                "population": "RV",
                "margin_of_error": 4.14,
                "undecided_pct": 17.0,
                "source_url": PA_WIKI_SOURCE,
                "results": {"Josh Shapiro": 54.0, "Stacy Garrity": 29.0},
            },
        ],
    },
    "oh": {
        "state_name": "Ohio",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_Ohio_gubernatorial_election",
        # Open seat: Mike DeWine (R) is term-limited. Ramaswamy declared
        # Feb 25, 2025; polls before that date tested a hypothetical
        # matchup and are cited to the Wikipedia polling table (no separate
        # press release located). All toplines/dates/samples as published.
        "candidates": [
            {"name": "Vivek Ramaswamy", "party": "Republican", "incumbent": False},
            {"name": "Amy Acton", "party": "Democratic", "incumbent": False},
        ],
        "raw_polls": [
            {
                "pollster": "Public Policy Polling",
                "sponsor": "Democratic",
                "field_start_date": "2025-02-19",
                "field_end_date": "2025-02-20",
                "release_date": "2025-02-24",
                "sample_size": 642,
                "population": "RV",
                "margin_of_error": 3.9,
                "undecided_pct": 11.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 44.0, "Amy Acton": 45.0},
            },
            {
                "pollster": "Bowling Green State University/YouGov",
                "sponsor": None,
                "field_start_date": "2025-04-18",
                "field_end_date": "2025-04-24",
                "release_date": "2025-04-28",
                "sample_size": 800,
                "population": "RV",
                "margin_of_error": 4.1,
                "undecided_pct": 5.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 50.0, "Amy Acton": 45.0},
            },
            {
                "pollster": "Impact Research",
                "sponsor": "Democratic",
                "field_start_date": "2025-07-24",
                "field_end_date": "2025-07-28",
                "release_date": "2025-08-01",
                "sample_size": 800,
                "population": "LV",
                "margin_of_error": 3.5,
                "undecided_pct": 7.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 47.0, "Amy Acton": 46.0},
            },
            {
                "pollster": "Emerson College",
                "sponsor": None,
                "field_start_date": "2025-08-18",
                "field_end_date": "2025-08-19",
                "release_date": "2025-08-21",
                "sample_size": 1000,
                "population": "RV",
                "margin_of_error": 3.0,
                "undecided_pct": 12.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 49.0, "Amy Acton": 39.0},
            },
            {
                "pollster": "Hart Research",
                "sponsor": "Democratic",
                "field_start_date": "2025-09-19",
                "field_end_date": "2025-09-22",
                "release_date": "2025-09-26",
                "sample_size": 800,
                "population": "LV",
                "margin_of_error": 3.0,
                "undecided_pct": 9.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 45.0, "Amy Acton": 46.0},
            },
            {
                "pollster": "Bowling Green State University/YouGov",
                "sponsor": None,
                "field_start_date": "2025-10-02",
                "field_end_date": "2025-10-14",
                "release_date": "2025-10-18",
                "sample_size": 800,
                "population": "RV",
                "margin_of_error": 4.5,
                "undecided_pct": 3.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 50.0, "Amy Acton": 47.0},
            },
            {
                "pollster": "Data Targeting",
                "sponsor": "Republican",
                "field_start_date": "2025-12-03",
                "field_end_date": "2025-12-08",
                "release_date": "2025-12-12",
                "sample_size": 603,
                "population": "LV",
                "margin_of_error": 4.0,
                "undecided_pct": 12.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 45.0, "Amy Acton": 43.0},
            },
            {
                "pollster": "Emerson College",
                "sponsor": None,
                "field_start_date": "2025-12-06",
                "field_end_date": "2025-12-08",
                "release_date": "2025-12-10",
                "sample_size": 850,
                "population": "RV",
                "margin_of_error": 3.3,
                "undecided_pct": 9.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 45.0, "Amy Acton": 46.0},
            },
            {
                "pollster": "EMC Research",
                "sponsor": "Democratic",
                "field_start_date": "2026-02-10",
                "field_end_date": "2026-02-22",
                "release_date": "2026-02-26",
                "sample_size": 1343,
                "population": "LV",
                "margin_of_error": 2.7,
                "undecided_pct": 4.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 43.0, "Amy Acton": 53.0},
            },
            {
                "pollster": "Quantus Insights",
                "sponsor": "Republican",
                "field_start_date": "2026-03-13",
                "field_end_date": "2026-03-14",
                "release_date": "2026-03-17",
                "sample_size": 809,
                "population": "LV",
                "margin_of_error": 3.8,
                "undecided_pct": 9.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 45.0, "Amy Acton": 46.0},
            },
            {
                "pollster": "Echelon Insights",
                "sponsor": "Republican",
                "field_start_date": "2026-04-03",
                "field_end_date": "2026-04-09",
                "release_date": "2026-04-12",
                "sample_size": 413,
                "population": "LV",
                "margin_of_error": 5.8,
                "undecided_pct": 7.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 49.0, "Amy Acton": 44.0},
            },
            {
                "pollster": "Bowling Green State University/YouGov",
                "sponsor": None,
                "field_start_date": "2026-04-07",
                "field_end_date": "2026-04-14",
                "release_date": "2026-04-18",
                "sample_size": 1000,
                "population": "RV",
                "margin_of_error": 4.5,
                "undecided_pct": 5.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 48.0, "Amy Acton": 47.0},
            },
            {
                "pollster": "Beacon Research/Shaw & Co. Research",
                "sponsor": None,
                "field_start_date": "2026-05-28",
                "field_end_date": "2026-06-01",
                "release_date": "2026-06-04",
                "sample_size": 1015,
                "population": "RV",
                "margin_of_error": 3.0,
                "undecided_pct": 1.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 49.0, "Amy Acton": 50.0},
            },
            {
                "pollster": "Tulchin Research",
                "sponsor": "Democratic",
                "field_start_date": "2026-06-02",
                "field_end_date": "2026-06-04",
                "release_date": "2026-06-07",
                "sample_size": 600,
                "population": "LV",
                "margin_of_error": 4.0,
                "undecided_pct": 9.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 44.0, "Amy Acton": 47.0},
            },
            {
                "pollster": "Fabrizio Ward/Impact Research",
                "sponsor": "AARP",
                "field_start_date": "2026-06-14",
                "field_end_date": "2026-06-16",
                "release_date": "2026-06-19",
                "sample_size": 800,
                "population": "LV",
                "margin_of_error": 3.5,
                "undecided_pct": 9.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 44.0, "Amy Acton": 47.0},
            },
            {
                "pollster": "New York Times/Siena University",
                "sponsor": None,
                "field_start_date": "2026-06-15",
                "field_end_date": "2026-06-28",
                "release_date": "2026-07-01",
                "sample_size": 601,
                "population": "LV",
                "margin_of_error": 4.7,
                "undecided_pct": 6.0,
                "source_url": OH_WIKI_SOURCE,
                "results": {"Vivek Ramaswamy": 47.0, "Amy Acton": 47.0},
            },
        ],
    },
    "ga": {
        "state_name": "Georgia",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_Georgia_gubernatorial_election",
        # Open seat: Brian Kemp (R) is term-limited. General campaign only
        # began after the June 16 runoff, so the polling table is short so
        # far. All cited to the Wikipedia polling table itself, since a
        # separate press release wasn't located for any of them.
        "candidates": [
            {"name": "Rick Jackson", "party": "Republican", "incumbent": False},
            {"name": "Keisha Lance Bottoms", "party": "Democratic", "incumbent": False},
        ],
        "raw_polls": [
            {
                "pollster": "Echelon Insights",
                "sponsor": "Republican",
                "field_start_date": "2026-04-03",
                "field_end_date": "2026-04-09",
                "release_date": "2026-04-13",
                "sample_size": 407,
                "population": "LV",
                "margin_of_error": 6.5,
                "undecided_pct": 8.0,
                "source_url": GA_WIKI_SOURCE,
                "results": {"Rick Jackson": 43.0, "Keisha Lance Bottoms": 49.0},
            },
            {
                "pollster": "Concord Public Opinion Partners",
                "sponsor": "Democratic",
                "field_start_date": "2026-05-30",
                "field_end_date": "2026-06-02",
                "release_date": "2026-06-05",
                "sample_size": 510,
                "population": "LV",
                "margin_of_error": 4.3,
                "undecided_pct": 9.0,
                "source_url": GA_WIKI_SOURCE,
                "results": {"Rick Jackson": 38.0, "Keisha Lance Bottoms": 53.0},
            },
            {
                "pollster": "Beacon Research/Shaw & Co. Research",
                "sponsor": None,
                "field_start_date": "2026-06-23",
                "field_end_date": "2026-06-27",
                "release_date": "2026-06-30",
                "sample_size": 1002,
                "population": "RV",
                "margin_of_error": 3.0,
                "undecided_pct": 1.0,
                "source_url": GA_WIKI_SOURCE,
                "results": {"Rick Jackson": 47.0, "Keisha Lance Bottoms": 52.0},
            },
            {
                "pollster": "Wick",
                "sponsor": None,
                "field_start_date": "2026-06-27",
                "field_end_date": "2026-06-30",
                "release_date": "2026-07-03",
                "sample_size": 1175,
                "population": "LV",
                "margin_of_error": 2.9,
                "undecided_pct": 14.0,
                "source_url": GA_WIKI_SOURCE,
                "results": {"Rick Jackson": 43.0, "Keisha Lance Bottoms": 43.0},
            },
        ],
    },
    "me": {
        "state_name": "Maine",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_Maine_gubernatorial_election",
        # Open seat: Janet Mills (D) is term-limited (Maine caps governors at
        # 2 consecutive terms). Both parties' nominations were settled by
        # Maine's standard ranked-choice-voting primary on June 9-19, 2026:
        # Pingree defeated Nirav Shah in the Democratic primary, and Charles
        # defeated Ben Midgley in the Republican primary. (A separate,
        # non-binding April 25 GOP convention straw poll was won by Midgley,
        # not Charles -- that straw poll wasn't the actual nomination.)
        # Independent state Sen. Rick Bennett (a former Maine Senate
        # president and former state GOP chair) also qualified for the
        # November ballot; both polls below tested a Pingree-vs-Charles
        # head-to-head (the NYT/Siena poll separately tested a 3-way
        # question with Bennett at 8%, not used here), so Bennett's support
        # is folded into undecided_pct along with true undecideds, the same
        # convention used for third-party/"Other" shares in PA/OH/GA.
        "candidates": [
            {"name": "Bobby Charles", "party": "Republican", "incumbent": False},
            {"name": "Hannah Pingree", "party": "Democratic", "incumbent": False},
        ],
        "raw_polls": [
            {
                "pollster": "Fox News/Beacon Research/Shaw & Co. Research",
                "sponsor": None,
                "field_start_date": "2026-06-23",
                "field_end_date": "2026-06-27",
                "release_date": "2026-06-30",
                "sample_size": 1003,
                "population": "RV",
                "margin_of_error": 3.0,
                "undecided_pct": 5.0,
                "source_url": "https://static.foxnews.com/foxnews.com/content/uploads/2026/06/fox_june-23-27-2026_complete_maine_topline_june-30-release.pdf",
                "results": {"Bobby Charles": 42.0, "Hannah Pingree": 53.0},
            },
            {
                "pollster": "New York Times/Portland Press Herald/Siena University",
                "sponsor": None,
                "field_start_date": "2026-06-19",
                "field_end_date": "2026-06-26",
                "release_date": "2026-06-30",
                "sample_size": 608,
                "population": "LV",
                "margin_of_error": 4.8,
                "undecided_pct": 5.0,
                "source_url": "https://www.pressherald.com/2026/06/30/hannah-pingree-is-the-heavy-favorite-in-maine-governors-race-times-press-herald-siena-poll-finds/",
                "results": {"Bobby Charles": 40.0, "Hannah Pingree": 55.0},
            },
        ],
    },
    "ia": {
        "state_name": "Iowa",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_Iowa_gubernatorial_election",
        # Open seat: Kim Reynolds (R) announced in April 2025 she would not
        # seek a third full term. The June 2, 2026 primary settled both
        # nominations: Zach Lahn (R) narrowly upset Trump-endorsed Rep. Randy
        # Feenstra, and Rob Sand (D, state auditor) ran unopposed.
        "candidates": [
            {"name": "Zach Lahn", "party": "Republican", "incumbent": False},
            {"name": "Rob Sand", "party": "Democratic", "incumbent": False},
        ],
        "raw_polls": [
            {
                "pollster": "Siena College/New York Times",
                "sponsor": None,
                "field_start_date": "2026-06-15",
                "field_end_date": "2026-06-27",
                "release_date": "2026-07-01",
                "sample_size": 600,
                "population": "LV",
                "margin_of_error": 5.0,
                "undecided_pct": 5.0,
                "source_url": "https://www.thegazette.com/news/elections/national/polls-iowa-s-u-s-senate-campaign-tight-sand-leads-for-governor/article_c9e86be1-a2cc-4dfe-a417-a6a3270388e6.html",
                "results": {"Zach Lahn": 47.0, "Rob Sand": 48.0},
            },
            {
                "pollster": "Fox News/Beacon Research/Shaw & Co. Research",
                "sponsor": None,
                "field_start_date": "2026-06-23",
                "field_end_date": "2026-06-27",
                "release_date": "2026-07-01",
                "sample_size": 1003,
                "population": "RV",
                "margin_of_error": 3.0,
                "undecided_pct": 3.0,
                "source_url": "https://static.foxnews.com/foxnews.com/content/uploads/2026/07/fox_june-23-27-2026_complete_iowa_topline_july-1-release.pdf",
                "results": {"Zach Lahn": 44.0, "Rob Sand": 53.0},
            },
        ],
    },
    "ny": {
        "state_name": "New York",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_New_York_gubernatorial_election",
        # Incumbent Kathy Hochul (D) is running for reelection; Lt. Gov.
        # Antonio Delgado's primary challenge fizzled and he withdrew Feb
        # 10, 2026. Bruce Blakeman (R), Nassau County executive, is the
        # Republican nominee (Rep. Elise Stefanik withdrew from that primary
        # Dec 19, 2025). Both ran unopposed in the June 23, 2026 primary.
        "candidates": [
            {"name": "Bruce Blakeman", "party": "Republican", "incumbent": False},
            {"name": "Kathy Hochul", "party": "Democratic", "incumbent": True},
        ],
        # Only polls fielded after Stefanik's Dec 19, 2025 withdrawal are
        # used, since earlier polls tested a hypothetical Hochul-vs-Stefanik
        # matchup rather than the real nominees. Exact release dates are
        # cited where an original press release/PDF was located (all 3
        # Siena releases used here); where only the field dates were
        # confirmed, release_date is approximated as field_end + a few days
        # (that pollster's typical turnaround) and cited to the Wikipedia
        # polling table itself, same convention used for PA's PennLive/MAD
        # Global Strategy polls.
        "raw_polls": [
            {
                "pollster": "Siena College",
                "sponsor": None,
                "field_start_date": "2026-01-26",
                "field_end_date": "2026-01-28",
                "release_date": "2026-02-02",
                "sample_size": 802,
                "population": "RV",
                "margin_of_error": 4.3,
                "undecided_pct": 18.0,
                "source_url": NY_WIKI_SOURCE,
                "results": {"Bruce Blakeman": 28.0, "Kathy Hochul": 54.0},
            },
            {
                "pollster": "Marist University",
                "sponsor": None,
                "field_start_date": "2026-02-16",
                "field_end_date": "2026-02-19",
                "release_date": "2026-02-23",
                "sample_size": 1442,
                "population": "RV",
                "margin_of_error": 3.3,
                "undecided_pct": 17.0,
                "source_url": "https://maristpoll.marist.edu/polls/the-state-of-new-york-in-an-election-year-february-2026/",
                "results": {"Bruce Blakeman": 33.0, "Kathy Hochul": 50.0},
            },
            {
                "pollster": "Siena College",
                "sponsor": None,
                "field_start_date": "2026-02-23",
                "field_end_date": "2026-02-26",
                "release_date": "2026-03-02",
                "sample_size": 805,
                "population": "RV",
                "margin_of_error": 4.5,
                "undecided_pct": 18.0,
                "source_url": NY_WIKI_SOURCE,
                "results": {"Bruce Blakeman": 31.0, "Kathy Hochul": 51.0},
            },
            {
                "pollster": "McLaughlin & Associates",
                "sponsor": "Republican",
                "field_start_date": "2026-03-04",
                "field_end_date": "2026-03-08",
                "release_date": "2026-03-11",
                "sample_size": 800,
                "population": "LV",
                "margin_of_error": 3.5,
                "undecided_pct": 5.0,
                "source_url": NY_WIKI_SOURCE,
                "results": {"Bruce Blakeman": 43.0, "Kathy Hochul": 52.0},
            },
            {
                "pollster": "Siena College",
                "sponsor": None,
                "field_start_date": "2026-03-23",
                "field_end_date": "2026-03-26",
                "release_date": "2026-03-31",
                "sample_size": 804,
                "population": "RV",
                "margin_of_error": 4.5,
                "undecided_pct": 19.0,
                "source_url": "https://sri.siena.edu/2026/03/31/hochul-lead-over-still-largely-unknown-blakeman-drops-7-points-to-47-34-from-51-31-her-favorability-approval-ratings-unchanged-in-last-month/",
                "results": {"Bruce Blakeman": 34.0, "Kathy Hochul": 47.0},
            },
            {
                "pollster": "Siena College",
                "sponsor": None,
                "field_start_date": "2026-04-27",
                "field_end_date": "2026-04-30",
                "release_date": "2026-05-05",
                "sample_size": 806,
                "population": "RV",
                "margin_of_error": 4.2,
                "undecided_pct": 18.0,
                "source_url": "https://sri.siena.edu/2026/05/05/hochul-favorability-approval-ratings-each-drop-8-points-to-lowest-levels-in-last-year-her-lead-over-blakeman-grows-3-points-to-49-33/",
                "results": {"Bruce Blakeman": 33.0, "Kathy Hochul": 49.0},
            },
            {
                "pollster": "Pollfinity Research",
                "sponsor": None,
                "field_start_date": "2026-06-11",
                "field_end_date": "2026-06-14",
                "release_date": "2026-06-17",
                "sample_size": 229,
                "population": "RV",
                "margin_of_error": 6.5,
                "undecided_pct": 10.0,
                "source_url": "https://www.opinionsandratings.com/picks-for-you/new-york-governor-election-polls",
                "results": {"Bruce Blakeman": 40.0, "Kathy Hochul": 50.0},
            },
            {
                "pollster": "Siena College",
                "sponsor": None,
                "field_start_date": "2026-06-17",
                "field_end_date": "2026-06-23",
                "release_date": "2026-06-25",
                "sample_size": 1120,
                "population": "RV",
                "margin_of_error": 3.6,
                "undecided_pct": 16.0,
                "source_url": "https://sri.siena.edu/2026/06/25/hochul-favorability-approval-ratings-edge-up-as-does-her-general-election-lead-over-blakeman-now-52-32-from-49-33/",
                "results": {"Bruce Blakeman": 32.0, "Kathy Hochul": 52.0},
            },
            {
                "pollster": "co/efficient",
                "sponsor": "Republican",
                "field_start_date": "2026-06-30",
                "field_end_date": "2026-07-02",
                "release_date": "2026-07-06",
                "sample_size": 1085,
                "population": "LV",
                "margin_of_error": 3.0,
                "undecided_pct": 12.0,
                "source_url": NY_WIKI_SOURCE,
                "results": {"Bruce Blakeman": 41.0, "Kathy Hochul": 47.0},
            },
        ],
    },
    "sc": {
        "state_name": "South Carolina",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_South_Carolina_gubernatorial_election",
        # Open seat: Henry McMaster (R) is barred from a third consecutive
        # elected term. AG Alan Wilson (R) defeated Lt. Gov. Pamela Evette in
        # a June 23, 2026 runoff after the June 9 primary; state Rep.
        # Jermaine Johnson (D) won his primary outright. No third-party/
        # independent complication in this matchup.
        "candidates": [
            {"name": "Alan Wilson", "party": "Republican", "incumbent": False},
            {"name": "Jermaine Johnson", "party": "Democratic", "incumbent": False},
        ],
        # No real general-election trial-heat poll of Wilson vs. Johnson has
        # been published as of 2026-07-11 -- the runoff was barely 3 weeks
        # ago. Left empty rather than substituting the primary/runoff polls
        # (which measured a different, intra-Republican electorate) or
        # fabricating one; the forecast falls back to a fundamentals-only
        # estimate (see app.services.forecasting.generate_forecast) until a
        # real poll is published and picked up by the live scraper.
        "raw_polls": [],
    },
    "tx": {
        "state_name": "Texas",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_Texas_gubernatorial_election",
        # Abbott (R) is running for a 4th term (no TX gubernatorial term
        # limits), won the March 3, 2026 primary outright with 82%. State
        # Rep. Gina Hinojosa (D) won a 9-way Democratic primary with 59%, no
        # runoff needed. Both nominations settled well before today.
        "candidates": [
            {"name": "Greg Abbott", "party": "Republican", "incumbent": True},
            {"name": "Gina Hinojosa", "party": "Democratic", "incumbent": False},
        ],
        # Release dates aren't independently confirmed for most of these
        # (only field dates were), so they're approximated as field_end + a
        # few days' typical turnaround and cited to the Wikipedia polling
        # table itself (cross-checked against its raw wikitext, which
        # carries per-row citations to each pollster's own release).
        "raw_polls": [
            {
                "pollster": "Siena College/New York Times",
                "sponsor": None,
                "field_start_date": "2026-06-19",
                "field_end_date": "2026-06-27",
                "release_date": "2026-06-30",
                "sample_size": 656,
                "population": "LV",
                "margin_of_error": 4.5,
                "undecided_pct": 5.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 51.0, "Gina Hinojosa": 44.0},
            },
            {
                "pollster": "SoCal Strategies",
                "sponsor": "Republican",
                "field_start_date": "2026-06-21",
                "field_end_date": "2026-06-21",
                "release_date": "2026-06-24",
                "sample_size": 800,
                "population": "LV",
                "margin_of_error": None,
                "undecided_pct": 4.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 54.0, "Gina Hinojosa": 42.0},
            },
            {
                "pollster": "University of Texas/Texas Politics Project",
                "sponsor": None,
                "field_start_date": "2026-06-05",
                "field_end_date": "2026-06-12",
                "release_date": "2026-06-15",
                "sample_size": 1200,
                "population": "RV",
                "margin_of_error": 2.8,
                "undecided_pct": 13.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 47.0, "Gina Hinojosa": 40.0},
            },
            {
                "pollster": "Quantus Insights",
                "sponsor": "Republican",
                "field_start_date": "2026-06-03",
                "field_end_date": "2026-06-04",
                "release_date": "2026-06-07",
                "sample_size": 800,
                "population": "LV",
                "margin_of_error": 3.5,
                "undecided_pct": 10.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 49.0, "Gina Hinojosa": 41.0},
            },
            {
                "pollster": "Texas A&M University/ReconMR",
                "sponsor": None,
                "field_start_date": "2026-06-01",
                "field_end_date": "2026-06-04",
                "release_date": "2026-06-07",
                "sample_size": 807,
                "population": "LV",
                "margin_of_error": 4.0,
                "undecided_pct": 8.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 49.0, "Gina Hinojosa": 43.0},
            },
            {
                "pollster": "Slingshot Strategies",
                "sponsor": "Democratic",
                "field_start_date": "2026-05-27",
                "field_end_date": "2026-05-28",
                "release_date": "2026-05-31",
                "sample_size": 1670,
                "population": "LV",
                "margin_of_error": 2.8,
                "undecided_pct": 13.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 46.0, "Gina Hinojosa": 41.0},
            },
            {
                "pollster": "Public Policy Polling",
                "sponsor": "Democratic",
                "field_start_date": "2026-05-22",
                "field_end_date": "2026-05-23",
                "release_date": "2026-05-26",
                "sample_size": 643,
                "population": "RV",
                "margin_of_error": None,
                "undecided_pct": 8.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 48.0, "Gina Hinojosa": 44.0},
            },
            {
                "pollster": "Texas Southern University/YouGov",
                "sponsor": None,
                "field_start_date": "2026-04-22",
                "field_end_date": "2026-05-05",
                "release_date": "2026-05-08",
                "sample_size": 1223,
                "population": "LV",
                "margin_of_error": 2.8,
                "undecided_pct": 8.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 49.0, "Gina Hinojosa": 43.0},
            },
            {
                "pollster": "Slingshot Strategies",
                "sponsor": "Democratic",
                "field_start_date": "2026-04-17",
                "field_end_date": "2026-04-20",
                "release_date": "2026-04-23",
                "sample_size": 1018,
                "population": "LV",
                "margin_of_error": 3.3,
                "undecided_pct": 9.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 48.0, "Gina Hinojosa": 43.0},
            },
            {
                "pollster": "University of Texas/Texas Politics Project",
                "sponsor": None,
                "field_start_date": "2026-04-10",
                "field_end_date": "2026-04-20",
                "release_date": "2026-04-23",
                "sample_size": 1200,
                "population": "RV",
                "margin_of_error": 2.8,
                "undecided_pct": 18.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 44.0, "Gina Hinojosa": 38.0},
            },
            {
                "pollster": "UT Tyler",
                "sponsor": None,
                "field_start_date": "2026-02-13",
                "field_end_date": "2026-02-22",
                "release_date": "2026-02-25",
                "sample_size": 1117,
                "population": "RV",
                "margin_of_error": 3.1,
                "undecided_pct": 10.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 49.0, "Gina Hinojosa": 41.0},
            },
            {
                "pollster": "University of Texas/Texas Politics Project",
                "sponsor": None,
                "field_start_date": "2026-02-02",
                "field_end_date": "2026-02-16",
                "release_date": "2026-02-19",
                "sample_size": 1300,
                "population": "RV",
                "margin_of_error": 5.1,
                "undecided_pct": 20.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 45.0, "Gina Hinojosa": 35.0},
            },
            {
                "pollster": "GBAO",
                "sponsor": "Democratic",
                "field_start_date": "2026-01-26",
                "field_end_date": "2026-02-03",
                "release_date": "2026-02-06",
                "sample_size": 1000,
                "population": "LV",
                "margin_of_error": 3.1,
                "undecided_pct": 11.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 46.0, "Gina Hinojosa": 43.0},
            },
            {
                "pollster": "University of Houston/YouGov",
                "sponsor": None,
                "field_start_date": "2026-01-20",
                "field_end_date": "2026-01-31",
                "release_date": "2026-02-03",
                "sample_size": 1502,
                "population": "LV",
                "margin_of_error": 2.5,
                "undecided_pct": 9.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 49.0, "Gina Hinojosa": 42.0},
            },
            {
                "pollster": "Emerson College",
                "sponsor": None,
                "field_start_date": "2026-01-10",
                "field_end_date": "2026-01-12",
                "release_date": "2026-01-15",
                "sample_size": 1165,
                "population": "RV",
                "margin_of_error": 2.8,
                "undecided_pct": 8.0,
                "source_url": TX_WIKI_SOURCE,
                "results": {"Greg Abbott": 50.0, "Gina Hinojosa": 42.0},
            },
        ],
    },
    "fl": {
        "state_name": "Florida",
        "office": "Governor",
        "election_date": "2026-11-03",
        "wikipedia_page_title": "2026_Florida_gubernatorial_election",
        # Open seat: Ron DeSantis (R) is term-limited. Neither primary is
        # LEGALLY decided yet -- Florida's primary is August 18, 2026,
        # still weeks away as of this writing -- but Byron Donalds (R,
        # Trump-endorsed) and David Jolly (D, a former Republican
        # congressman who became a Democrat) are used as presumptive
        # nominees per explicit direction: Donalds dominates every neutral
        # poll against his declared primary rivals (Lt. Gov. Jay Collins,
        # ex-House Speaker Paul Renner), and Jolly's only serious rival
        # (Orange County Mayor Jerry Demings) suspended his campaign June
        # 5, 2026 after a cancer diagnosis, leaving only minor candidates.
        "candidates": [
            {"name": "Byron Donalds", "party": "Republican", "incumbent": False},
            {"name": "David Jolly", "party": "Democratic", "incumbent": False},
        ],
        "raw_polls": [
            {
                "pollster": "James Madison Institute",
                "sponsor": "Republican",
                "field_start_date": "2026-02-13",
                "field_end_date": "2026-02-16",
                "release_date": "2026-02-19",
                "sample_size": 1200,
                "population": "RV",
                "margin_of_error": 2.77,
                "undecided_pct": 23.0,
                "source_url": "https://floridapolitics.com/archives/758095-byron-donalds-paul-renner-both-hold-edge-barely-over-david-jolly-in-poll-from-jmi/",
                "results": {"Byron Donalds": 41.0, "David Jolly": 36.0},
            },
            {
                "pollster": "Emerson College",
                "sponsor": None,
                "field_start_date": "2026-03-29",
                "field_end_date": "2026-03-31",
                "release_date": "2026-04-03",
                "sample_size": 1125,
                "population": "LV",
                "margin_of_error": 2.8,
                "undecided_pct": 17.0,
                "source_url": "https://emersoncollegepolling.com/florida-2026-poll-donalds-leads-gop-primary-for-governor-republicans-outpace-democrats-in-florida-elections/",
                "results": {"Byron Donalds": 44.0, "David Jolly": 39.0},
            },
            {
                "pollster": "Change Research",
                "sponsor": None,
                "field_start_date": "2026-05-13",
                "field_end_date": "2026-05-16",
                "release_date": "2026-05-19",
                "sample_size": 1593,
                "population": "LV",
                "margin_of_error": None,
                "undecided_pct": 12.0,
                "source_url": "https://changeresearch.com/florida-governors-race-may-2026/",
                "results": {"Byron Donalds": 42.0, "David Jolly": 46.0},
            },
            {
                "pollster": "Change Research",
                # Sponsor listed as "Freedom Project USA" in the release,
                # but its political orientation couldn't be independently
                # confirmed -- left unset rather than asserting a lean.
                "sponsor": None,
                "field_start_date": "2026-06-11",
                "field_end_date": "2026-06-14",
                "release_date": "2026-06-17",
                "sample_size": 1015,
                "population": "LV",
                "margin_of_error": None,
                "undecided_pct": 8.0,
                "source_url": "https://changeresearch.com/wp-content/uploads/2026/06/Florida-June-Poll-Memo.pdf",
                "results": {"Byron Donalds": 43.0, "David Jolly": 49.0},
            },
        ],
    },
}
